
-- local tile_names = require "api.tile_names"


local tile_names_for_hexes = {
    "stone-path",
    "concrete",
    "hazard-concrete-left",
    "hazard-concrete-right",
    "refined-concrete",
    "refined-hazard-concrete-left",
    "refined-hazard-concrete-right",
    "red-refined-concrete",
    "green-refined-concrete",
    "blue-refined-concrete",
    "orange-refined-concrete",
    "yellow-refined-concrete",
    "pink-refined-concrete",
    "purple-refined-concrete",
    "black-refined-concrete",
    "brown-refined-concrete",
    "cyan-refined-concrete",
    "acid-refined-concrete",
}


data:extend({
    -- HIGH GAMEPLAY IMPACT SETTINGS
    {
        type = "bool-setting",
        name = "hextorio-nauvis-filled-edges",
        setting_type = "runtime-global",
        default_value = false,
        order = "a[important]-m[deathworld]-f[nauvis-filled-edges]",
    },
    {
        type = "bool-setting",
        name = "hextorio-nauvis-grace",
        setting_type = "runtime-global",
        default_value = false,
        order = "a[important]-m[deathworld]-f[nauvis-grace]",
    },

    -- STARTUP SETTINGS
    {
        type = "int-setting",
        name = "hextorio-planet-size-nauvis",
        setting_type = "startup",
        default_value = 48,
        minimum_value = 1,
        maximum_value = 100,
        order = "h[hex-grid]-d[terrain]-s[planet-size]-p[nauvis]",
    },
    {
        type = "string-setting",
        name = "hextorio-grid-rotation-mode-nauvis",
        setting_type = "startup",
        default_value = "flat-top",
        allowed_values = {"random", "flat-top", "pointed-top"},
        order="h[hex-grid]-d[terrain]-s[rotation-mode]-p[nauvis]",
    },
    {
        type = "double-setting",
        name = "hextorio-hex-size-nauvis",
        setting_type = "startup",
        default_value = 24,
        minimum_value = 8,
        maximum_value = 60,
        order="h[hex-grid]-d[terrain]-s[hex-size]-p[nauvis]",
    },
    {
        type = "int-setting",
        name = "hextorio-hex-stroke-width-nauvis",
        setting_type = "startup",
        default_value = 3,
        minimum_value = 2,
        maximum_value = 32,
        order="h[hex-grid]-d[terrain]-s[stroke-width]-p[nauvis]",
    },
    {
        type = "int-setting",
        name = "hextorio-planet-size-vulcanus",
        setting_type = "startup",
        default_value = 30,
        minimum_value = 1,
        maximum_value = 100,
        order = "h[hex-grid]-d[terrain]-s[planet-size]-p[vulcanus]",
    },
    {
        type = "string-setting",
        name = "hextorio-grid-rotation-mode-vulcanus",
        setting_type = "startup",
        default_value = "pointed-top",
        allowed_values = {"random", "flat-top", "pointed-top"},
        order="h[hex-grid]-d[terrain]-s[rotation-mode]-p[vulcanus]",
    },
    {
        type = "double-setting",
        name = "hextorio-hex-size-vulcanus",
        setting_type = "startup",
        default_value = 40,
        minimum_value = 8,
        maximum_value = 60,
        order="h[hex-grid]-d[terrain]-s[hex-size]-p[vulcanus]",
    },
    {
        type = "int-setting",
        name = "hextorio-hex-stroke-width-vulcanus",
        setting_type = "startup",
        default_value = 3,
        minimum_value = 2,
        maximum_value = 32,
        order="h[hex-grid]-d[terrain]-s[stroke-width]-p[vulcanus]",
    },
    {
        type = "int-setting",
        name = "hextorio-planet-size-fulgora",
        setting_type = "startup",
        default_value = 30,
        minimum_value = 1,
        maximum_value = 100,
        order = "h[hex-grid]-d[terrain]-s[planet-size]-q[fulgora]",
    },
    {
        type = "string-setting",
        name = "hextorio-grid-rotation-mode-fulgora",
        setting_type = "startup",
        default_value = "pointed-top",
        allowed_values = {"random", "flat-top", "pointed-top"},
        order="h[hex-grid]-d[terrain]-s[rotation-mode]-q[fulgora]",
    },
    {
        type = "double-setting",
        name = "hextorio-hex-size-fulgora",
        setting_type = "startup",
        default_value = 33,
        minimum_value = 8,
        maximum_value = 60,
        order="h[hex-grid]-d[terrain]-s[hex-size]-q[fulgora]",
    },
    {
        type = "int-setting",
        name = "hextorio-hex-stroke-width-fulgora",
        setting_type = "startup",
        default_value = 9,
        minimum_value = 2,
        maximum_value = 32,
        order="h[hex-grid]-d[terrain]-s[stroke-width]-q[fulgora]",
    },
    {
        type = "int-setting",
        name = "hextorio-planet-size-gleba",
        setting_type = "startup",
        default_value = 36,
        minimum_value = 1,
        maximum_value = 100,
        order = "h[hex-grid]-d[terrain]-s[planet-size]-q[gleba]",
    },
    {
        type = "string-setting",
        name = "hextorio-grid-rotation-mode-gleba",
        setting_type = "startup",
        default_value = "pointed-top",
        allowed_values = {"random", "flat-top", "pointed-top"},
        order="h[hex-grid]-d[terrain]-s[rotation-mode]-q[gleba]",
    },
    {
        type = "double-setting",
        name = "hextorio-hex-size-gleba",
        setting_type = "startup",
        default_value = 34,
        minimum_value = 8,
        maximum_value = 60,
        order="h[hex-grid]-d[terrain]-s[hex-size]-q[gleba]",
    },
    {
        type = "int-setting",
        name = "hextorio-hex-stroke-width-gleba",
        setting_type = "startup",
        default_value = 10,
        minimum_value = 2,
        maximum_value = 32,
        order="h[hex-grid]-d[terrain]-s[stroke-width]-q[gleba]",
    },
    {
        type = "int-setting",
        name = "hextorio-planet-size-aquilo",
        setting_type = "startup",
        default_value = 24,
        minimum_value = 1,
        maximum_value = 100,
        order = "h[hex-grid]-d[terrain]-s[planet-size]-r[aquilo]",
    },
    {
        type = "string-setting",
        name = "hextorio-grid-rotation-mode-aquilo",
        setting_type = "startup",
        default_value = "random",
        allowed_values = {"random", "flat-top", "pointed-top"},
        order="h[hex-grid]-d[terrain]-s[rotation-mode]-r[aquilo]",
    },
    {
        type = "double-setting",
        name = "hextorio-hex-size-aquilo",
        setting_type = "startup",
        default_value = 50,
        minimum_value = 8,
        maximum_value = 60,
        order="h[hex-grid]-d[terrain]-s[hex-size]-r[aquilo]",
    },
    {
        type = "int-setting",
        name = "hextorio-hex-stroke-width-aquilo",
        setting_type = "startup",
        default_value = 20,
        minimum_value = 2,
        maximum_value = 32,
        order="h[hex-grid]-d[terrain]-s[stroke-width]-r[aquilo]",
    },

    -- RUNTIME SETTINGS
    {
        type = "double-setting",
        name = "hextorio-hex-claim-cost-mult-nauvis",
        setting_type = "runtime-global",
        default_value = 1.0,
        minimum_value = 0.0001,
        maximum_value = 10000,
        order="h[hex-grid]-a[hex-claim-cost]-p[nauvis]",
    },
    {
        type = "double-setting",
        name = "hextorio-hex-claim-cost-mult-vulcanus",
        setting_type = "runtime-global",
        default_value = 1.0,
        minimum_value = 0.0001,
        maximum_value = 10000,
        order="h[hex-grid]-a[hex-claim-cost]-p[vulcanus]",
    },
    {
        type = "double-setting",
        name = "hextorio-hex-claim-cost-mult-fulgora",
        setting_type = "runtime-global",
        default_value = 1.0,
        minimum_value = 0.0001,
        maximum_value = 10000,
        order="h[hex-grid]-a[hex-claim-cost]-q[fulgora]",
    },
    {
        type = "double-setting",
        name = "hextorio-hex-claim-cost-mult-gleba",
        setting_type = "runtime-global",
        default_value = 1.0,
        minimum_value = 0.0001,
        maximum_value = 10000,
        order="h[hex-grid]-a[hex-claim-cost]-q[gleba]",
    },
    {
        type = "double-setting",
        name = "hextorio-hex-claim-cost-mult-aquilo",
        setting_type = "runtime-global",
        default_value = 1.0,
        minimum_value = 0.0001,
        maximum_value = 10000,
        order="h[hex-grid]-a[hex-claim-cost]-r[aquilo]",
    },
    {
        type = "color-setting",
        name = "hextorio-dungeon-hexlight-color",
        setting_type = "runtime-global",
        default_value = {0.85, 0.25, 0.1},
        order="h[hex-grid]-b[hexlight-color]-l[dungeon]",
    },
    {
        type = "color-setting",
        name = "hextorio-default-nauvis-hexlight-color",
        setting_type = "runtime-global",
        default_value = {0.65, 0.56, 0.4},
        order="h[hex-grid]-b[hexlight-color]-p[nauvis]",
    },
    {
        type = "color-setting",
        name = "hextorio-default-vulcanus-hexlight-color",
        setting_type = "runtime-global",
        default_value = {0.51, 0.4, 0.25},
        order="h[hex-grid]-b[hexlight-color]-p[vulcanus]",
    },
    {
        type = "color-setting",
        name = "hextorio-default-fulgora-hexlight-color",
        setting_type = "runtime-global",
        default_value = {1, 0.78, 0.96},
        order="h[hex-grid]-b[hexlight-color]-q[fulgora]",
    },
    {
        type = "color-setting",
        name = "hextorio-default-gleba-hexlight-color",
        setting_type = "runtime-global",
        default_value = {0.14, 0.33, 0.4},
        order="h[hex-grid]-b[hexlight-color]-q[gleba]",
    },
    {
        type = "color-setting",
        name = "hextorio-default-aquilo-hexlight-color",
        setting_type = "runtime-global",
        default_value = {0.35, 0.44, 0.31},
        order="h[hex-grid]-b[hexlight-color]-r[aquilo]",
    },
    {
        type = "double-setting",
        name = "hextorio-vault-chance",
        setting_type = "runtime-global",
        default_value = 0.02,
        minimum_value = 0,
        maximum_value = 1.0,
        order="h[hex-grid]-c[fulgora-misc]-s[vault-chance]",
    },
    {
        type = "double-setting",
        name = "hextorio-fulgoran-attractor-chance",
        setting_type = "runtime-global",
        default_value = 0.25,
        minimum_value = 0,
        maximum_value = 1.0,
        order="h[hex-grid]-c[fulgora-misc]-t[attractor-chance]",
    },
    {
        type = "double-setting",
        name = "hextorio-small-egg-raft-chance",
        setting_type = "runtime-global",
        default_value = 0.25,
        minimum_value = 0,
        maximum_value = 1.0,
        order="h[hex-grid]-c[gleba-misc]-s[small-egg-raft-chance]",
    },

    {
        type = "double-setting",
        name = "hextorio-tiles-per-quality-nauvis",
        setting_type = "runtime-global",
        default_value = 8.0,
        minimum_value = 1.0,
        order="h[hex-grid]-k[quality]-s[tiles-per-quality]-p[nauvis]",
    },
    {
        type = "double-setting",
        name = "hextorio-tiles-per-quality-vulcanus",
        setting_type = "runtime-global",
        default_value = 5.0,
        minimum_value = 1.0,
        order="h[hex-grid]-k[quality]-s[tiles-per-quality]-p[vulcanus]",
    },
    {
        type = "double-setting",
        name = "hextorio-tiles-per-quality-fulgora",
        setting_type = "runtime-global",
        default_value = 5.0,
        minimum_value = 1.0,
        order="h[hex-grid]-k[quality]-s[tiles-per-quality]-q[fulgora]",
    },
    {
        type = "double-setting",
        name = "hextorio-tiles-per-quality-gleba",
        setting_type = "runtime-global",
        default_value = 6.0,
        minimum_value = 1.0,
        order="h[hex-grid]-k[quality]-s[tiles-per-quality]-q[gleba]",
    },
    {
        type = "double-setting",
        name = "hextorio-tiles-per-quality-aquilo",
        setting_type = "runtime-global",
        default_value = 4.0,
        minimum_value = 1.0,
        order="h[hex-grid]-k[quality]-s[tiles-per-quality]-r[aquilo]",
    },

    -- RUNTIME (PERFORMANCE)
    {
        type = "int-setting",
        name = "hextorio-hex-pool-size",
        setting_type = "runtime-global",
        default_value = 25,
        minimum_value = 1,
        order = "z[performance]-s[hex-pool]-a[pool-size]",
    },

    -- PLAYER SETTINGS
    {
        type = "string-setting",
        name = "hextorio-claimed-hex-tile",
        setting_type = "runtime-per-user",
        default_value = "refined-concrete",
        allowed_values = tile_names_for_hexes,
        order="h[hex-grid]-d[tile]-s[claimed-hex]",
    },
    {
        type = "string-setting",
        name = "hextorio-edge-fill-tile",
        setting_type = "runtime-per-user",
        default_value = "black-refined-concrete",
        allowed_values = tile_names_for_hexes,
        order="h[hex-grid]-d[tile]-s[edge-fill]",
    },
})
