
require "settings.hex_grid"
require "settings.dungeons"
require "settings.resources"
require "settings.item_values"
require "settings.trades"
require "settings.item_ranks"
require "settings.misc"
require "settings.notifications"
require "settings.item_buffs"
