
data:extend({
    {
        type = "double-setting",
        name = "hextorio-base-resource-richness",
        setting_type = "runtime-global",
        default_value = 1.0,
        minimum_value = 0.01,
        maximum_value = 100.0,
        order = "da",
    },
    {
        type = "double-setting",
        name = "hextorio-resource-richness-per-dist",
        setting_type = "runtime-global",
        default_value = 50.0,
        minimum_value = -1000.0,
        maximum_value = 1000.0,
        order = "db",
    },

    {
        type = "double-setting",
        name = "hextorio-iron-ore-frequency",
        setting_type = "runtime-global",
        default_value = 6.0,
        minimum_value = 0.0,
        maximum_value = 24.0,
        order = "ga",
    },
    {
        type = "double-setting",
        name = "hextorio-copper-ore-frequency",
        setting_type = "runtime-global",
        default_value = 4.5,
        minimum_value = 0.0,
        maximum_value = 24.0,
        order = "gb",
    },
    {
        type = "double-setting",
        name = "hextorio-coal-frequency",
        setting_type = "runtime-global",
        default_value = 2.5,
        minimum_value = 0.0,
        maximum_value = 24.0,
        order = "gc",
    },
    {
        type = "double-setting",
        name = "hextorio-stone-frequency",
        setting_type = "runtime-global",
        default_value = 2.0,
        minimum_value = 0.0,
        maximum_value = 24.0,
        order = "gd",
    },
    {
        type = "double-setting",
        name = "hextorio-crude-oil-frequency",
        setting_type = "runtime-global",
        default_value = 1.0,
        minimum_value = 0.0,
        maximum_value = 24.0,
        order = "ge",
    },
    {
        type = "double-setting",
        name = "hextorio-uranium-ore-frequency",
        setting_type = "runtime-global",
        default_value = 1.0,
        minimum_value = 0.0,
        maximum_value = 24.0,
        order = "gf",
    },

    {
        type = "int-setting",
        name = "hextorio-min-uranium-dist",
        setting_type = "runtime-global",
        default_value = 4,
        minimum_value = 1,
        maximum_value = 100,
        order = "ia",
    },

    {
        type = "double-setting",
        name = "hextorio-resource-bias",
        setting_type = "runtime-global",
        default_value = 0,
        order = "ja",
    },
    {
        type = "bool-setting",
        name = "hextorio-resource-bias-variation",
        setting_type = "runtime-global",
        default_value = true,
        order = "jb",
    },

    {
        type = "double-setting",
        name = "hextorio-starting-hex-resource-stroke-width",
        setting_type = "runtime-global",
        default_value = 2.0,
        minimum_value = 1.0,
        maximum_value = 10.0,
        order = "ka",
    },
    {
        type = "double-setting",
        name = "hextorio-resource-width-per-dist",
        setting_type = "runtime-global",
        default_value = 0.125,
        order = "kb",
    },

    {
        type = "bool-setting",
        name = "hextorio-starting-resources-mixed",
        setting_type = "runtime-global",
        default_value = true,
        order = "ma",
    },
    {
        type = "bool-setting",
        name = "hextorio-default-resources-mixed",
        setting_type = "runtime-global",
        default_value = true,
        order = "mb",
    },
})
