
data:extend({
    {
        type = "string-setting",
        name = "hextorio-ore-generation-mode",
        setting_type = "runtime-global",
        allowed_values = {"single-hex", "along-edges", "center-square"},
        default_value = "along-edges",
        order = "w[resources]-b[ore-generation-mode]",
    },
    {
        type = "double-setting",
        name = "hextorio-base-resource-richness",
        setting_type = "runtime-global",
        default_value = 1.0,
        minimum_value = 0.01,
        maximum_value = 100.0,
        order = "w[resources]-c[base-resource-richness]",
    },

    {
        type = "double-setting",
        name = "hextorio-resource-richness-per-dist-nauvis",
        setting_type = "runtime-global",
        default_value = 50.0,
        minimum_value = -1000.0,
        maximum_value = 1000.0,
        order = "w[resources]-i[richness-per-dist]-p[nauvis]",
    },
    {
        type = "double-setting",
        name = "hextorio-resource-richness-per-dist-vulcanus",
        setting_type = "runtime-global",
        default_value = 75.0,
        minimum_value = -1000.0,
        maximum_value = 1000.0,
        order = "w[resources]-i[richness-per-dist]-p[vulcanus]",
    },
    {
        type = "double-setting",
        name = "hextorio-resource-richness-per-dist-fulgora",
        setting_type = "runtime-global",
        default_value = 100.0,
        minimum_value = -1000.0,
        maximum_value = 1000.0,
        order = "w[resources]-i[richness-per-dist]-q[fulgora]",
    },
    {
        type = "double-setting",
        name = "hextorio-resource-richness-per-dist-gleba",
        setting_type = "runtime-global",
        default_value = 25.0,
        minimum_value = -1000.0,
        maximum_value = 1000.0,
        order = "w[resources]-i[richness-per-dist]-q[gleba]",
    },
    {
        type = "double-setting",
        name = "hextorio-resource-richness-per-dist-aquilo",
        setting_type = "runtime-global",
        default_value = 50.0,
        minimum_value = -1000.0,
        maximum_value = 1000.0,
        order = "w[resources]-i[richness-per-dist]-r[aquilo]",
    },

    {
        type = "double-setting",
        name = "hextorio-iron-ore-frequency",
        setting_type = "runtime-global",
        default_value = 6.0,
        minimum_value = 0.0,
        maximum_value = 24.0,
        order = "w[resources]-k[frequency]-p[nauvis]-t[iron-ore]",
    },
    {
        type = "double-setting",
        name = "hextorio-copper-ore-frequency",
        setting_type = "runtime-global",
        default_value = 4.5,
        minimum_value = 0.0,
        maximum_value = 24.0,
        order = "w[resources]-k[frequency]-p[nauvis]-u[copper-ore]",
    },
    {
        type = "double-setting",
        name = "hextorio-nauvis-coal-frequency",
        setting_type = "runtime-global",
        default_value = 2.5,
        minimum_value = 0.0,
        maximum_value = 24.0,
        order = "w[resources]-k[frequency]-p[nauvis]-v[coal]",
    },
    {
        type = "double-setting",
        name = "hextorio-nauvis-stone-frequency",
        setting_type = "runtime-global",
        default_value = 2.0,
        minimum_value = 0.0,
        maximum_value = 24.0,
        order = "w[resources]-k[frequency]-p[nauvis]-v[stone]",
    },
    {
        type = "double-setting",
        name = "hextorio-nauvis-crude-oil-frequency",
        setting_type = "runtime-global",
        default_value = 1.0,
        minimum_value = 0.0,
        maximum_value = 24.0,
        order = "w[resources]-k[frequency]-p[nauvis]-w[crude-oil]",
    },
    {
        type = "double-setting",
        name = "hextorio-uranium-ore-frequency",
        setting_type = "runtime-global",
        default_value = 1.0,
        minimum_value = 0.0,
        maximum_value = 24.0,
        order = "w[resources]-k[frequency]-p[nauvis]-w[uranium-ore]",
    },
    {
        type = "double-setting",
        name = "hextorio-vulcanus-coal-frequency",
        setting_type = "runtime-global",
        default_value = 3.0,
        minimum_value = 0.0,
        maximum_value = 24.0,
        order = "w[resources]-k[frequency]-p[vulcanus]-t[coal]",
    },
    {
        type = "double-setting",
        name = "hextorio-calcite-frequency",
        setting_type = "runtime-global",
        default_value = 0.5,
        minimum_value = 0.0,
        maximum_value = 24.0,
        order = "w[resources]-k[frequency]-p[vulcanus]-u[calcite]",
    },
    {
        type = "double-setting",
        name = "hextorio-tungsten-ore-frequency",
        setting_type = "runtime-global",
        default_value = 0.5,
        minimum_value = 0.0,
        maximum_value = 24.0,
        order = "w[resources]-k[frequency]-p[vulcanus]-u[tungsten]",
    },
    {
        type = "double-setting",
        name = "hextorio-tungsten-bias-chance",
        setting_type = "runtime-global",
        default_value = 0.1,
        minimum_value = 0.0,
        maximum_value = 1.0,
        order = "w[resources]-k[frequency]-p[vulcanus]-u[tungsten-bias-chance]",
    },
    {
        type = "double-setting",
        name = "hextorio-aquilo-crude-oil-frequency",
        setting_type = "runtime-global",
        default_value = 1.0,
        minimum_value = 0.0,
        maximum_value = 24.0,
        order = "w[resources]-k[frequency]-r[aquilo]-t[crude-oil]",
    },
    {
        type = "double-setting",
        name = "hextorio-lithium-brine-frequency",
        setting_type = "runtime-global",
        default_value = 3.0,
        minimum_value = 0.0,
        maximum_value = 24.0,
        order = "w[resources]-k[frequency]-r[aquilo]-t[lithium-brine]",
    },
    {
        type = "double-setting",
        name = "hextorio-fluorine-vent-frequency",
        setting_type = "runtime-global",
        default_value = 3.0,
        minimum_value = 0.0,
        maximum_value = 24.0,
        order = "w[resources]-k[frequency]-r[aquilo]-u[fluorine-vent]",
    },

    {
        type = "double-setting",
        name = "hextorio-resource-frequency-dropoff-nauvis",
        setting_type = "runtime-global",
        default_value = 0.075,
        order = "w[resources]-l[frequency-dropoff]-p[nauvis]",
    },
    {
        type = "double-setting",
        name = "hextorio-resource-frequency-dropoff-vulcanus",
        setting_type = "runtime-global",
        default_value = 0.075,
        order = "w[resources]-l[frequency-dropoff]-p[vulcanus]",
    },
    {
        type = "double-setting",
        name = "hextorio-resource-frequency-dropoff-fulgora",
        setting_type = "runtime-global",
        default_value = 0.05,
        order = "w[resources]-l[frequency-dropoff]-q[fulgora]",
    },
    {
        type = "double-setting",
        name = "hextorio-resource-frequency-dropoff-gleba",
        setting_type = "runtime-global",
        default_value = 0.1,
        order = "w[resources]-l[frequency-dropoff]-q[gleba]",
    },
    {
        type = "double-setting",
        name = "hextorio-resource-frequency-dropoff-aquilo",
        setting_type = "runtime-global",
        default_value = 0.15,
        order = "w[resources]-l[frequency-dropoff]-r[aquilo]",
    },

    {
        type = "int-setting",
        name = "hextorio-min-uranium-dist",
        setting_type = "runtime-global",
        default_value = 4,
        minimum_value = 1,
        maximum_value = 100,
        order = "w[resources]-m[min-dist]-p[nauvis]-t[uranium-ore]",
    },
    {
        type = "int-setting",
        name = "hextorio-min-tungsten-dist",
        setting_type = "runtime-global",
        default_value = 6,
        minimum_value = 1,
        maximum_value = 100,
        order = "w[resources]-m[min-dist]-p[vulcanus]-t[tungsten-ore]",
    },

    {
        type = "double-setting",
        name = "hextorio-starting-hex-resource-stroke-width-nauvis",
        setting_type = "runtime-global",
        default_value = 2.0,
        minimum_value = 1.0,
        maximum_value = 10.0,
        order = "w[resources]-o[stroke-width]-a[starting]-p[nauvis]",
    },
    {
        type = "double-setting",
        name = "hextorio-starting-hex-resource-stroke-width-vulcanus",
        setting_type = "runtime-global",
        default_value = 7.0,
        minimum_value = 1.0,
        maximum_value = 10.0,
        order = "w[resources]-o[stroke-width]-a[starting]-p[vulcanus]",
    },
    {
        type = "double-setting",
        name = "hextorio-starting-hex-resource-stroke-width-fulgora",
        setting_type = "runtime-global",
        default_value = 3.0,
        minimum_value = 1.0,
        maximum_value = 10.0,
        order = "w[resources]-o[stroke-width]-a[starting]-q[fulgora]",
    },
    {
        type = "double-setting",
        name = "hextorio-starting-hex-resource-stroke-width-gleba",
        setting_type = "runtime-global",
        default_value = 4.0,
        minimum_value = 1.0,
        maximum_value = 10.0,
        order = "w[resources]-o[stroke-width]-a[starting]-q[gleba]",
    },
    {
        type = "double-setting",
        name = "hextorio-base-resource-width-nauvis",
        setting_type = "runtime-global",
        default_value = 1,
        minimum_value = 1,
        order = "w[resources]-o[stroke-width]-b[base]-p[nauvis]",
    },
    {
        type = "double-setting",
        name = "hextorio-base-resource-width-vulcanus",
        setting_type = "runtime-global",
        default_value = 4,
        minimum_value = 1,
        order = "w[resources]-o[stroke-width]-b[base]-p[vulcanus]",
    },
    {
        type = "double-setting",
        name = "hextorio-base-resource-width-fulgora",
        setting_type = "runtime-global",
        default_value = 3,
        minimum_value = 1,
        order = "w[resources]-o[stroke-width]-b[base]-q[fulgora]",
    },
    {
        type = "double-setting",
        name = "hextorio-base-resource-width-gleba",
        setting_type = "runtime-global",
        default_value = 4,
        minimum_value = 1,
        order = "w[resources]-o[stroke-width]-b[base]-q[gleba]",
    },
    {
        type = "double-setting",
        name = "hextorio-resource-width-per-dist-nauvis",
        setting_type = "runtime-global",
        default_value = 0.125,
        order = "w[resources]-o[stroke-width]-b[increment]-p[nauvis]",
    },
    {
        type = "double-setting",
        name = "hextorio-resource-width-per-dist-vulcanus",
        setting_type = "runtime-global",
        default_value = 0.375,
        order = "w[resources]-o[stroke-width]-b[increment]-p[vulcanus]",
    },
    {
        type = "double-setting",
        name = "hextorio-resource-width-per-dist-fulgora",
        setting_type = "runtime-global",
        default_value = 0.125,
        order = "w[resources]-o[stroke-width]-b[increment]-q[fulgora]",
    },
    {
        type = "double-setting",
        name = "hextorio-resource-width-per-dist-gleba",
        setting_type = "runtime-global",
        default_value = 0.125,
        order = "w[resources]-o[stroke-width]-b[increment]-q[gleba]",
    },
    {
        type = "double-setting",
        name = "hextorio-resource-width-max-nauvis",
        setting_type = "runtime-global",
        minimum_value = 1,
        default_value = 8,
        order = "w[resources]-o[stroke-width]-b[max]-p[nauvis]",
    },
    {
        type = "double-setting",
        name = "hextorio-resource-width-max-vulcanus",
        setting_type = "runtime-global",
        minimum_value = 1,
        default_value = 16,
        order = "w[resources]-o[stroke-width]-b[max]-p[vulcanus]",
    },
    {
        type = "double-setting",
        name = "hextorio-resource-width-max-fulgora",
        setting_type = "runtime-global",
        minimum_value = 1,
        default_value = 6,
        order = "w[resources]-o[stroke-width]-b[max]-q[fulgora]",
    },
    {
        type = "double-setting",
        name = "hextorio-resource-width-max-gleba",
        setting_type = "runtime-global",
        default_value = 12,
        minimum_value = 1,
        order = "w[resources]-o[stroke-width]-b[max]-q[gleba]",
    },

    {
        type = "bool-setting",
        name = "hextorio-starting-resources-mixed",
        setting_type = "runtime-global",
        default_value = true,
        order = "w[resources]-q[starting-resources-mixed]",
    },
    {
        type = "bool-setting",
        name = "hextorio-default-resources-mixed",
        setting_type = "runtime-global",
        default_value = true,
        order = "w[resources]-r[default-resources-mixed]",
    },
    {
        type = "double-setting",
        name = "hextorio-resource-bias",
        setting_type = "runtime-global",
        default_value = 2.0,
        order = "w[resources]-r[resource-bias]",
    },
    {
        type = "bool-setting",
        name = "hextorio-resource-bias-variation",
        setting_type = "runtime-global",
        default_value = true,
        order = "w[resources]-s[resource-bias-variation]",
    },

    {
        type = "double-setting",
        name = "hextorio-supercharge-cost-per-tile",
        setting_type = "runtime-global",
        minimum_value = 0,
        default_value = 50,
        order = "w[resources]-t[costs]-s[supercharge]-g[per-tile]",
    },
    {
        type = "double-setting",
        name = "hextorio-supercharge-cost-per-well",
        setting_type = "runtime-global",
        minimum_value = 0,
        default_value = 400000,
        order = "w[resources]-t[costs]-s[supercharge]-g[per-well]",
    },
    {
        type = "double-setting",
        name = "hextorio-supercharge-cost-multiplier",
        setting_type = "runtime-global",
        minimum_value = 0,
        default_value = 0.005,
        order = "w[resources]-t[costs]-s[supercharge]-h[multiplier]",
    },
    {
        type = "double-setting",
        name = "hextorio-resource-conversion-cost-multiplier",
        setting_type = "runtime-global",
        minimum_value = 0,
        default_value = 100,
        order = "w[resources]-t[costs]-t[conversion]-h[multiplier]",
    },
})
