
data:extend({
    {
        type = "double-setting",
        name = "hextorio-base-trade-efficiency",
        setting_type = "runtime-global",
        default_value = 0.8,
        minimum_value = 0.1,
        maximum_value = 10,
        order = "a[important]-a[balancing]-s[base-trade-efficiency]",
    },
    {
        type = "double-setting",
        name = "hextorio-trade-efficiency-per-item",
        setting_type = "runtime-global",
        default_value = 0.07,
        minimum_value = -1,
        maximum_value = 1,
        order = "a[important]-a[balancing]-s[trade-efficiency-per-item]",
    },
    {
        type = "string-setting",
        name = "hextorio-trade-complexity",
        setting_type = "runtime-global",
        default_value = "balanced",
        allowed_values = {"simple", "balanced", "complex"},
        order = "a[important]-a[balancing]-t[trade-complexity]",
    },
    {
        type = "double-setting",
        setting_type = "runtime-global",
        name = "hextorio-unresearched-penalty",
        default_value = 5,
        minimum_value = -10,
        maximum_value = 100,
        order = "a[important]-a[balancing]-t[unresearched-penalty]",
    },
    {
        type = "bool-setting",
        setting_type = "runtime-global",
        name = "hextorio-allow-two-headed-trains",
        default_value = false,
        order = "a[important]-b[balancing]-u[allow-two-headed-trains]",
    },

    {
        type = "double-setting",
        name = "hextorio-coin-trade-chance",
        setting_type = "runtime-global",
        default_value = 0.3,
        minimum_value = 0,
        maximum_value = 1.0,
        order = "t[trades]-c[coin-trade-chance]",
    },
    {
        type = "double-setting",
        name = "hextorio-sell-trade-chance",
        setting_type = "runtime-global",
        default_value = 0.5,
        minimum_value = 0,
        maximum_value = 1.0,
        order = "t[trades]-c[sell-trade-chance]",
    },
    {
        type = "double-setting",
        name = "hextorio-sink-generator-efficiency",
        setting_type = "runtime-global",
        default_value = 0.25,
        minimum_value = 0.1,
        maximum_value = 10.0,
        order = "t[trades]-c[sink-generator-efficiency]",
    },
    {
        type = "bool-setting",
        name = "hextorio-tournament-trades-enabled",
        setting_type = "runtime-global",
        default_value = false,
        order = "t[trades]-c[tournament]-a[enabled]",
    },
    {
        type = "string-setting",
        name = "hextorio-tournament-order-nauvis",
        setting_type = "runtime-global",
        default_value = "3",
        allowed_values = {"legacy", "3", "7", "19"},
        order = "t[trades]-c[tournament]-b[order]-p[nauvis]",
    },
    {
        type = "string-setting",
        name = "hextorio-tournament-order-vulcanus",
        setting_type = "runtime-global",
        default_value = "7",
        allowed_values = {"legacy", "3", "7", "19"},
        order = "t[trades]-c[tournament]-b[order]-p[vulcanus]",
    },
    {
        type = "string-setting",
        name = "hextorio-tournament-order-fulgora",
        setting_type = "runtime-global",
        default_value = "7",
        allowed_values = {"legacy", "3", "7", "19"},
        order = "t[trades]-c[tournament]-b[order]-q[fulgora]",
    },
    {
        type = "string-setting",
        name = "hextorio-tournament-order-gleba",
        setting_type = "runtime-global",
        default_value = "7",
        allowed_values = {"legacy", "3", "7", "19"},
        order = "t[trades]-c[tournament]-b[order]-q[gleba]",
    },
    {
        type = "string-setting",
        name = "hextorio-tournament-order-aquilo",
        setting_type = "runtime-global",
        default_value = "19",
        allowed_values = {"legacy", "3", "7", "19"},
        order = "t[trades]-c[tournament]-b[order]-r[aquilo]",
    },
    {
        type = "string-setting",
        name = "hextorio-tournament-coin-trade-policy",
        setting_type = "runtime-global",
        default_value = "legacy",
        allowed_values = {"legacy", "bin-coins", "unique-coin-bin"},
        order = "t[trades]-c[tournament]-c[coin-policy]",
    },
    {
        type = "int-setting",
        name = "hextorio-tournament-coin-bin-index",
        setting_type = "runtime-global",
        default_value = 1,
        minimum_value = 1,
        maximum_value = 19,
        order = "t[trades]-c[tournament]-d[coin-bin-index]",
    },
    {
        type = "string-setting",
        name = "hextorio-tournament-binning-mode",
        setting_type = "runtime-global",
        default_value = "recipe-value-clustering",
        allowed_values = {"value-sorted", "recipe-value-clustering", "wfc", "manual-debug"},
        order = "t[trades]-c[tournament]-e[binning-mode]",
    },
    {
        type = "string-setting",
        name = "hextorio-tournament-strictness",
        setting_type = "runtime-global",
        default_value = "fallback-legacy",
        allowed_values = {"strict", "fallback-legacy", "skip-invalid"},
        order = "t[trades]-c[tournament]-f[strictness]",
    },
    {
        type = "string-setting",
        name = "hextorio-tournament-efficiency-profile",
        setting_type = "runtime-global",
        default_value = "chord-penalty",
        allowed_values = {"off", "chord-penalty", "cycle-bonus-and-chord-penalty"},
        order = "t[trades]-c[tournament]-g[efficiency-profile]",
    },
    {
        type = "int-setting",
        name = "hextorio-trades-per-hex-nauvis",
        setting_type = "runtime-global",
        default_value = 2,
        minimum_value = 0,
        maximum_value = 10,
        order = "t[trades]-d[trades-per-hex]-p[nauvis]",
    },
    {
        type = "int-setting",
        name = "hextorio-trades-per-hex-vulcanus",
        setting_type = "runtime-global",
        default_value = 3,
        minimum_value = 0,
        maximum_value = 10,
        order = "t[trades]-d[trades-per-hex]-p[vulcanus]",
    },
    {
        type = "int-setting",
        name = "hextorio-trades-per-hex-fulgora",
        setting_type = "runtime-global",
        default_value = 4,
        minimum_value = 0,
        maximum_value = 10,
        order = "t[trades]-d[trades-per-hex]-q[fulgora]",
    },
    {
        type = "int-setting",
        name = "hextorio-trades-per-hex-gleba",
        setting_type = "runtime-global",
        default_value = 3,
        minimum_value = 0,
        maximum_value = 10,
        order = "t[trades]-d[trades-per-hex]-q[gleba]",
    },
    {
        type = "int-setting",
        name = "hextorio-trades-per-hex-aquilo",
        setting_type = "runtime-global",
        default_value = 2,
        minimum_value = 0,
        maximum_value = 10,
        order = "t[trades]-d[trades-per-hex]-r[aquilo]",
    },
    {
        type = "double-setting",
        setting_type = "runtime-global",
        name = "hextorio-quality-cost-multiplier",
        default_value = 1.5,
        minimum_value = 0.1,
        order = "t[trades]-d[balancing]-s[quality-cost-multiplier]",
    },

    {
        type = "double-setting",
        name = "hextorio-base-trade-prod-nauvis",
        setting_type = "runtime-global",
        default_value = 0,
        minimum_value = -10,
        maximum_value = 10,
        order = "t[trades]-p[base-prod]-p[nauvis]",
    },
    {
        type = "double-setting",
        name = "hextorio-base-trade-prod-vulcanus",
        setting_type = "runtime-global",
        default_value = 0.05,
        minimum_value = -10,
        maximum_value = 10,
        order = "t[trades]-p[base-prod]-p[vulcanus]",
    },
    {
        type = "double-setting",
        name = "hextorio-base-trade-prod-fulgora",
        setting_type = "runtime-global",
        default_value = 0.10,
        minimum_value = -10,
        maximum_value = 10,
        order = "t[trades]-p[base-prod]-q[fulgora]",
    },
    {
        type = "double-setting",
        name = "hextorio-base-trade-prod-gleba",
        setting_type = "runtime-global",
        default_value = 0.15,
        minimum_value = -10,
        maximum_value = 10,
        order = "t[trades]-p[base-prod]-q[gleba]",
    },
    {
        type = "double-setting",
        name = "hextorio-base-trade-prod-aquilo",
        setting_type = "runtime-global",
        default_value = 0.20,
        minimum_value = -10,
        maximum_value = 10,
        order = "t[trades]-p[base-prod]-r[aquilo]",
    },

    {
        type = "bool-setting",
        name = "hextorio-increment-trade-quality",
        setting_type = "runtime-global",
        default_value = true,
        order = "t[trades]-u[increment-trade-quality]",
    },

    {
        type = "int-setting",
        name = "hextorio-trade-batching-threshold",
        setting_type = "runtime-global",
        default_value = 3000,
        minimum_value = 100,
        order = "z[performance]-s[trade-batching-threshold]",
    },
    {
        type = "int-setting",
        name = "hextorio-trade-collection-batch-size",
        setting_type = "runtime-global",
        default_value = 2000,
        minimum_value = 1,
        order = "z[performance]-s[trade-collection-batch-size]",
    },
    {
        type = "int-setting",
        name = "hextorio-trade-filtering-batch-size",
        setting_type = "runtime-global",
        default_value = 500,
        minimum_value = 1,
        order = "z[performance]-s[trade-filtering-batch-size]",
    },
    {
        type = "int-setting",
        name = "hextorio-trade-sorting-batch-size",
        setting_type = "runtime-global",
        default_value = 2000,
        minimum_value = 1,
        order = "z[performance]-s[trade-sorting-batch-size]",
    },
})
