
data:extend({
    {
        type = "double-setting",
        name = "hextorio-base-trade-efficiency",
        setting_type = "runtime-global",
        default_value = 0.8,
        minimum_value = 0.1,
        maximum_value = 10,
        order = "a[important]-a[balancing]-s[base-trade-efficiency]",
    },
    {
        type = "double-setting",
        setting_type = "runtime-global",
        name = "hextorio-unresearched-penalty",
        default_value = 5,
        minimum_value = -10,
        maximum_value = 100,
        order = "a[important]-a[balancing]-s[unresearched-penalty]",
    },
    {
        type = "bool-setting",
        setting_type = "runtime-global",
        name = "hextorio-allow-two-headed-trains",
        default_value = true,
        order = "a[important]-b[balancing]-s[allow-two-headed-trains]",
    },

    {
        type = "double-setting",
        name = "hextorio-coin-trade-chance",
        setting_type = "runtime-global",
        default_value = 0.3,
        minimum_value = 0,
        maximum_value = 1.0,
        order = "t[trades]-c[coin-trade-chance]",
    },
    {
        type = "double-setting",
        name = "hextorio-sell-trade-chance",
        setting_type = "runtime-global",
        default_value = 0.4,
        minimum_value = 0,
        maximum_value = 1.0,
        order = "t[trades]-c[sell-trade-chance]",
    },
    {
        type = "int-setting",
        name = "hextorio-trades-per-hex-nauvis",
        setting_type = "runtime-global",
        default_value = 2,
        minimum_value = 0,
        maximum_value = 10,
        order = "t[trades]-d[trades-per-hex]-p[nauvis]",
    },
    {
        type = "int-setting",
        name = "hextorio-trades-per-hex-vulcanus",
        setting_type = "runtime-global",
        default_value = 3,
        minimum_value = 0,
        maximum_value = 10,
        order = "t[trades]-d[trades-per-hex]-p[vulcanus]",
    },
    {
        type = "int-setting",
        name = "hextorio-trades-per-hex-fulgora",
        setting_type = "runtime-global",
        default_value = 3,
        minimum_value = 0,
        maximum_value = 10,
        order = "t[trades]-d[trades-per-hex]-q[fulgora]",
    },
    {
        type = "int-setting",
        name = "hextorio-trades-per-hex-gleba",
        setting_type = "runtime-global",
        default_value = 3,
        minimum_value = 0,
        maximum_value = 10,
        order = "t[trades]-d[trades-per-hex]-q[gleba]",
    },
    {
        type = "int-setting",
        name = "hextorio-trades-per-hex-aquilo",
        setting_type = "runtime-global",
        default_value = 2,
        minimum_value = 0,
        maximum_value = 10,
        order = "t[trades]-d[trades-per-hex]-r[aquilo]",
    },
    {
        type = "double-setting",
        setting_type = "runtime-global",
        name = "hextorio-quality-cost-multiplier",
        default_value = 1.5,
        minimum_value = 0.1,
        order = "t[trades]-d[balancing]-s[quality-cost-multiplier]",
    },

    {
        type = "double-setting",
        name = "hextorio-base-trade-prod-nauvis",
        setting_type = "runtime-global",
        default_value = 0,
        minimum_value = -10,
        maximum_value = 10,
        order = "t[trades]-p[base-prod]-p[nauvis]",
    },
    {
        type = "double-setting",
        name = "hextorio-base-trade-prod-vulcanus",
        setting_type = "runtime-global",
        default_value = 0.05,
        minimum_value = -10,
        maximum_value = 10,
        order = "t[trades]-p[base-prod]-p[vulcanus]",
    },
    {
        type = "double-setting",
        name = "hextorio-base-trade-prod-fulgora",
        setting_type = "runtime-global",
        default_value = 0.10,
        minimum_value = -10,
        maximum_value = 10,
        order = "t[trades]-p[base-prod]-q[fulgora]",
    },
    {
        type = "double-setting",
        name = "hextorio-base-trade-prod-gleba",
        setting_type = "runtime-global",
        default_value = 0.15,
        minimum_value = -10,
        maximum_value = 10,
        order = "t[trades]-p[base-prod]-q[gleba]",
    },
    {
        type = "double-setting",
        name = "hextorio-base-trade-prod-aquilo",
        setting_type = "runtime-global",
        default_value = 0.20,
        minimum_value = -10,
        maximum_value = 10,
        order = "t[trades]-p[base-prod]-r[aquilo]",
    },

    {
        type = "bool-setting",
        name = "hextorio-increment-trade-quality",
        setting_type = "runtime-global",
        default_value = true,
        order = "t[trades]-u[increment-trade-quality]",
    },

    {
        type = "int-setting",
        name = "hextorio-trade-batching-threshold",
        setting_type = "runtime-global",
        default_value = 3000,
        minimum_value = 100,
        order = "z[performance]-s[trade-batching-threshold]",
    },
    {
        type = "int-setting",
        name = "hextorio-trade-collection-batch-size",
        setting_type = "runtime-global",
        default_value = 2000,
        minimum_value = 1,
        order = "z[performance]-s[trade-collection-batch-size]",
    },
    {
        type = "int-setting",
        name = "hextorio-trade-filtering-batch-size",
        setting_type = "runtime-global",
        default_value = 500,
        minimum_value = 1,
        order = "z[performance]-s[trade-filtering-batch-size]",
    },
    {
        type = "int-setting",
        name = "hextorio-trade-sorting-batch-size",
        setting_type = "runtime-global",
        default_value = 2000,
        minimum_value = 1,
        order = "z[performance]-s[trade-sorting-batch-size]",
    },
})
