
require("prototypes.item_subgroup")
require("prototypes.item")
require("prototypes.resource")
require("prototypes.sprite")
require("prototypes.recipe")
require("prototypes.entity")
require("prototypes.custom_inputs")
require("prototypes.selection_tool")
require("prototypes.shortcut")
require("prototypes.technology")
require("prototypes.combat_robot")
require("prototypes.projectile")
require("prototypes.equipment_grid")
require("prototypes.dungeon")
