
data:extend{
    {
        type = "sprite",
        name = "hex-coin",
        filename = "__hextorio__/graphics/icons/hex-coin.png",
        width = 64,
        height = 64,
    },
    {
        type = "sprite",
        name = "gravity-coin",
        filename = "__hextorio__/graphics/icons/gravity-coin.png",
        width = 64,
        height = 64,
    },
    {
        type = "sprite",
        name = "meteor-coin",
        filename = "__hextorio__/graphics/icons/meteor-coin.png",
        width = 64,
        height = 64,
    },
    {
        type = "sprite",
        name = "hexaprism-coin",
        filename = "__hextorio__/graphics/icons/hexaprism-coin.png",
        width = 64,
        height = 64,
    },
    {
        type = "sprite",
        name = "trade-arrow",
        filename = "__hextorio__/graphics/icons/trade-arrow.png",
        width = 150,
        height = 150,
        scale = 40/150,
    },
    {
        type = "sprite",
        name = "interplanetary-trade-arrow",
        filename = "__hextorio__/graphics/icons/trade-arrow-cyan.png",
        width = 150,
        height = 150,
        scale = 40/150,
    },
    {
        type = "sprite",
        name = "questbook",
        filename = "__hextorio__/graphics/icons/questbook.png",
        width = 128,
        height = 128,
    },
    {
        type = "sprite",
        name = "trade-overview",
        filename = "__hextorio__/graphics/icons/trade-overview.png",
        width = 128,
        height = 128,
    },
    {
        type = "sprite",
        name = "catalog",
        filename = "__hextorio__/graphics/icons/catalog.png",
        width = 128,
        height = 128,
    },
    {
        type = "sprite",
        name = "star-silhouette",
        filename = "__hextorio__/graphics/icons/star-silhouette.png",
        width = 128,
        height = 128,
    },
    {
        type = "sprite",
        name = "bronze-star",
        filename = "__hextorio__/graphics/icons/bronze-star.png",
        width = 128,
        height = 128,
    },
    {
        type = "sprite",
        name = "bronze-star-left-half",
        filename = "__hextorio__/graphics/icons/bronze-star-left-half.png",
        width = 128,
        height = 128,
    },
    {
        type = "sprite",
        name = "bronze-star-right-half",
        filename = "__hextorio__/graphics/icons/bronze-star-right-half.png",
        width = 128,
        height = 128,
    },
    {
        type = "sprite",
        name = "small-bronze-star",
        filename = "__hextorio__/graphics/icons/bronze-star-small.png",
        width = 24,
        height = 24,
    },
    {
        type = "sprite",
        name = "small-bronze-star-left-half",
        filename = "__hextorio__/graphics/icons/bronze-star-left-half-small.png",
        width = 24,
        height = 24,
    },
    {
        type = "sprite",
        name = "small-bronze-star-right-half",
        filename = "__hextorio__/graphics/icons/bronze-star-right-half-small.png",
        width = 24,
        height = 24,
    },
    {
        type = "sprite",
        name = "silver-star",
        filename = "__hextorio__/graphics/icons/silver-star.png",
        width = 128,
        height = 128,
    },
    {
        type = "sprite",
        name = "small-silver-star",
        filename = "__hextorio__/graphics/icons/silver-star-small.png",
        width = 24,
        height = 24,
    },
    {
        type = "sprite",
        name = "gold-star",
        filename = "__hextorio__/graphics/icons/gold-star.png",
        width = 128,
        height = 128,
    },
    {
        type = "sprite",
        name = "small-gold-star",
        filename = "__hextorio__/graphics/icons/gold-star-small.png",
        width = 24,
        height = 24,
    },
    {
        type = "sprite",
        name = "red-star",
        filename = "__hextorio__/graphics/icons/red-star.png",
        width = 128,
        height = 128,
    },
    {
        type = "sprite",
        name = "small-red-star",
        filename = "__hextorio__/graphics/icons/red-star-small.png",
        width = 24,
        height = 24,
    },
    {
        type = "sprite",
        name = "rank-1",
        filename = "__hextorio__/graphics/icons/rank-1.png",
        width = 62,
        height = 24,
    },
    {
        type = "sprite",
        name = "rank-1-bought",
        filename = "__hextorio__/graphics/icons/rank-1-bought.png",
        width = 62,
        height = 24,
    },
    {
        type = "sprite",
        name = "rank-1-sold",
        filename = "__hextorio__/graphics/icons/rank-1-sold.png",
        width = 62,
        height = 24,
    },
    {
        type = "sprite",
        name = "rank-2",
        filename = "__hextorio__/graphics/icons/rank-2.png",
        width = 62,
        height = 24,
    },
    {
        type = "sprite",
        name = "rank-3",
        filename = "__hextorio__/graphics/icons/rank-3.png",
        width = 62,
        height = 24,
    },
    {
        type = "sprite",
        name = "rank-4",
        filename = "__hextorio__/graphics/icons/rank-4.png",
        width = 62,
        height = 24,
    },
    {
        type = "sprite",
        name = "rank-5",
        filename = "__hextorio__/graphics/icons/rank-5.png",
        width = 62,
        height = 24,
    },
    {
        type = "sprite",
        name = "teleport",
        filename = "__hextorio__/graphics/icons/teleport.png",
        width = 128,
        height = 128,
    },
    {
        type = "sprite",
        name = "planet-nauvis",
        filename = "__hextorio__/graphics/icons/starmap-planet-nauvis.png",
        width = 96,
        height = 96,
    },
    {
        type = "sprite",
        name = "planet-vulcanus",
        filename = "__hextorio__/graphics/icons/starmap-planet-vulcanus.png",
        width = 96,
        height = 96,
    },
    {
        type = "sprite",
        name = "planet-fulgora",
        filename = "__hextorio__/graphics/icons/starmap-planet-fulgora.png",
        width = 96,
        height = 96,
    },
    {
        type = "sprite",
        name = "planet-gleba",
        filename = "__hextorio__/graphics/icons/starmap-planet-gleba.png",
        width = 96,
        height = 96,
    },
    {
        type = "sprite",
        name = "planet-aquilo",
        filename = "__hextorio__/graphics/icons/starmap-planet-aquilo.png",
        width = 96,
        height = 96,
    },
    {
        type = "sprite",
        name = "check-mark-green",
        filename = "__base__/graphics/icons/signal/signal-checked-green.png",
        width = 64,
        height = 64,
        scale = 0.5,
    },
    {
        type = "sprite",
        name = "red-ex",
        filename = "__base__/graphics/icons/signal/signal-deny.png",
        width = 64,
        height = 64,
        scale = 0.5,
    },
    {
        type = "sprite",
        name = "arrow-north",
        filename = "__hextorio__/graphics/icons/arrow-north.png",
        width = 128,
        height = 128,
    },
    {
        type = "sprite",
        name = "arrow-east",
        filename = "__hextorio__/graphics/icons/arrow-east.png",
        width = 128,
        height = 128,
    },
    {
        type = "sprite",
        name = "arrow-south",
        filename = "__hextorio__/graphics/icons/arrow-south.png",
        width = 128,
        height = 128,
    },
    {
        type = "sprite",
        name = "arrow-west",
        filename = "__hextorio__/graphics/icons/arrow-west.png",
        width = 128,
        height = 128,
    },
    {
        type = "sprite",
        name = "missing-quest-img",
        filename = "__hextorio__/graphics/icons/missing-quest-img.png",
        width = 256,
        height = 256,
    },
    {
        type = "sprite",
        name = "backpack",
        filename = "__hextorio__/graphics/icons/backpack.png",
        width = 64,
        height = 64,
    },
    {
        type = "sprite",
        name = "hand",
        filename = "__hextorio__/graphics/icons/hand.png",
        width = 64,
        height = 64,
    },
    {
        type = "sprite",
        name = "stack-one",
        filename = "__hextorio__/graphics/icons/stack-one.png",
        width = 64,
        height = 64,
    },
    {
        type = "sprite",
        name = "stack-full",
        filename = "__hextorio__/graphics/icons/stack-full.png",
        width = 64,
        height = 64,
    },
    {
        type = "sprite",
        name = "item-buff-enhance",
        filename = "__hextorio__/graphics/icons/item-buff-enhance.png",
        width = 64,
        height = 64,
    },
    {
        type = "sprite",
        name = "item-buff-unlock",
        filename = "__hextorio__/graphics/icons/padlock-unlocked.png",
        width = 64,
        height = 64,
    },
}

local data_quests = require "data.quests"

local quest_sprites = {}
for _, quest_def in pairs(data_quests.quest_defs) do
    if quest_def.has_img == nil or quest_def.has_img then
        table.insert(quest_sprites, {
            type = "sprite",
            name = "quest-" .. quest_def.name,
            filename = "__hextorio__/graphics/quest/" .. quest_def.name .. ".png",
            width = 256,
            height = 256,
        })
    end
end

data:extend(quest_sprites)
